In [1]:
import numpy as np

In [152]:
def convolucion(x,h):
    dif= np.abs(x.size-h.size)
    if len(x)< len(h):
        
        for i in range(0,dif):
            x= np.append(x,0)          
    elif x.size> h.size: 
        for i in range(0,dif): 
            h= np.append(h,0) 
    else:
        pass
    return x, np.flip(h)

In [166]:
x= np.array([0,0,0,1,1,1,1])
h= np.array([0,0,0,1,2,3,0])


In [192]:
def funcion(x,h):
    d=[]
    r= np.zeros(h.size+x.size-1)
    copy= np.insert(x,0,np.zeros(h.size -1))
    copy= np.insert(copy, copy.size, np.zeros(h.size-1))
    for n in np.arange(0, r.size):
        for m in np.arange(0,h.size):
            r[n]+= r[n]+h[m]*copy[m+n]
            d= np.append(d,r[n])
    print(d)
            


In [194]:
h.size

8

In [193]:
funcion(x,h)
#np.convolve(h,x)

[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   1.   2.   4.   8.
   0.   0.   0.   2.   5.  10.  20.  40.   0.   0.   3.   8.  17.  34.
  68. 136.   0.   0.   3.   8.  17.  34.  68. 136.   0.   0.   3.   8.
  16.  32.  64. 128.   0.   0.   3.   6.  12.  24.  48.  96.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]


In [177]:
np.convolve(h,x)

array([0, 0, 0, 0, 3, 5, 6, 6, 3, 1, 0, 0, 0])

In [167]:
x , h= convolucion(x,h)


In [155]:
h

array([0, 3, 2, 1, 0, 0, 0])

In [106]:
c=0
a= []
n=np.arange(0,len(h),1)
m=np.arange(0,len(x),1)
for i in n:
    for j in m:
        c = np.multiply(x,-h)
        s= sum(c)
        #c= np.multiply(x[j],h[i-j])
        
    print("c [",i,"]=", " ", s)       
 

c [ 0 ]=   -6
c [ 1 ]=   -6
c [ 2 ]=   -6
c [ 3 ]=   -6
c [ 4 ]=   -6
c [ 5 ]=   -6
c [ 6 ]=   -6


In [25]:
n

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,
        8.,  9., 10.])

In [55]:
l = np.arange(-5,10,1)

In [56]:
l

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [96]:
z= np.multiply(x,h)
sum(z)

6

In [181]:
c=0
a= []
n=np.arange(0,len(h),1)
m=np.arange(0,len(x),1)
for i in n:
    c = np.multiply(x,h)
    s= sum(c)
    np.delete(h,h.size-1)
    h=np.insert(h,0,0)
        
 

ValueError: operands could not be broadcast together with shapes (7,) (8,) 

In [144]:
h

array([0, 3, 2, 1, 0, 0, 0])

In [146]:
np.delete(h,len(h)-1)
h=np.insert(h,0,0)



In [151]:
h

array([0, 0, 3, 2, 1, 0, 0, 0])